In [1]:
import torch
import time

In [2]:
a = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.float32)

b = torch.tensor([[1,1],
                  [2,2],
                  [3,3]], dtype=torch.float32)

print("a size:", a.size(), "b size:", b.size())

a size: torch.Size([2, 3]) b size: torch.Size([3, 2])


In [4]:
ab = torch.mm(a, b)
print("a dot b = ", ab, "size = ", ab.size())

a dot b =  tensor([[14., 14.],
        [32., 32.]]) size =  torch.Size([2, 2])


In [5]:
batch_a = a.repeat(16,1,1)
batch_b = b.repeat(16,1,1)

print("batch size = 16")
print(batch_a.size())
print(batch_b.size())

batch size = 16
torch.Size([16, 2, 3])
torch.Size([16, 3, 2])


In [21]:
dot_ans = torch.bmm(batch_a, batch_b)
print(dot_ans.size())
dot_ans[:10]

torch.Size([16, 2, 2])


tensor([[[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]],

        [[14., 14.],
         [32., 32.]]])

In [12]:
flat_a = batch_a.view(32, 3)
flat_a[:8]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]])

In [17]:
flat_b = batch_b.view(3, 32)
flat_b[:8]

tensor([[1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3.,
         1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1.],
        [2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1.,
         2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2.],
        [3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2.,
         3., 3., 1., 1., 2., 2., 3., 3., 1., 1., 2., 2., 3., 3.]])

In [19]:
dot_ab = torch.mm(flat_a, flat_b)
dot_ab.view(512,2)[:10]

tensor([[14., 14.],
        [11., 11.],
        [11., 11.],
        [14., 14.],
        [11., 11.],
        [11., 11.],
        [14., 14.],
        [11., 11.],
        [11., 11.],
        [14., 14.]])

In [15]:
ans = []
for i in range(16):
    ans.append(torch.mm(batch_a[i], batch_b[i]))

ans = torch.stack(ans)
print(ans.size())

torch.Size([16, 2, 2])


In [6]:
batch_ab = torch.mm(batch_a, batch_b)

RuntimeError: matrices expected, got 3D, 3D tensors at /pytorch/aten/src/TH/generic/THTensorMath.cpp:747

In [1]:
import torch

a = torch.zeros([16, 32, 3, 25, 9], dtype=torch.float32)
#b = torch.zeros([16, 32, 3, 25, 9], dtype=torch.float32)

sunm_a = torch.sum(a, dim=2)
sunm_a.size()


torch.Size([16, 32, 25, 9])